### ISSUE TITLE
How can I use migrations?

### ISSUE THREAD

**Issue by ronaldaraujo** [alzen8work/ci_hmvc#1]
I'm trying to use migrations in your project, but I can not. I am putting the migrations in the "application/migrations" folder, however I get the following error message:

**No migrations were found.**

**Comment by IrcDirk** [comment]
Did u follow instructions at https://www.codeigniter.com/user_guide/libraries/migration.html ?

**Comment by ronaldaraujo** [comment]
Yes. But I did not get a solution in the documentation. Thank you anyway.
